repos:
  - repo: local
    hooks:
      - id: run-unittests
        name: Run Unittests
        entry: python -m unittest discover -s tests -p "test_*.py"
        language: system
        types: [python]
